@startuml
title AubieMemory Design Class Diagram

class Player {
mscore
incrementScore()
getScore()
}

class Game {
-mBlueButton
-mRedButton
-mYellowButton
-mGreenButton
-mPinkButton
-mLightBlueButton
-mOrangeButton
-mPurpleButton
-mBlueNote
-mRedNote
-mYellowNote
-mRedNote
-mVictorySound
-mLoseSound
-mCountDownTimer
setDifficulty()
setAudioSource()
selectButton()
unselectButton()
playTone()
computerPlayTone()
enableButtons()
checkCorrectInput()
setScore()
}

class MemoryActivity {
onCreate()
onPause()
onResume()
onAttach()
onBeginnerButtonPressed()
onIntermediateButtonPressed()
onExpertButtonPressed()
onScoreButtonPressed()
}

class HighScoreManager {
getHighScore()
setHighScore()
}

class ToneSequence {
-mToneSequence
-mCurrentToneIndex
toneSequence()
getNextTone()
addRandomTone()
getSize()
getCurrentToneIndex()
resetToneIndex()
clear()
isInputCorrect()
isSequenceFinished()
}

object Activity
object Fragment

Player - Game
Game -> Fragment
Game - MemoryActivity
Game - HighScoreManager
Game - ToneSequence
MemoryActivity -> Activity
@enduml