@startuml
title AubieMemory Domain Model

class Player {
score
}

class Button {
color
tone
picture
}

class Game {
}

class HighScoreManager {
difficulty
highScore
}

Game "1" *-- "8" Button: contains >

Player - HighScoreManager: views high score >
Player -- Button: presses >
Player -- Game: views >

hide empty members
hide methods
@enduml