@startuml
title AubieMemory System Sequence Diagram
actor Player
participant MemoryGame
participant HighScoreManager
group SD: Memory

Player -> MemoryGame: Choose difficulty
loop while (difficulty chosen)
Player <-- MemoryGame: RedButton
Player <-- MemoryGame: YellowButton
Player <-- MemoryGame: GreenButton
Player <-- MemoryGame: BlueButton
Player <-- MemoryGame: PinkButton
Player <-- MemoryGame: LightBlueButton
Player <-- MemoryGame: OrangeButton
Player <-- MemoryGame: PurpleButton
else

opt correct input
Player -> MemoryGame: input sequence
Player <- MemoryGame: extended sequence
end
end

Player <-- MemoryGame: Score
MemoryGame --> HighScoreManager: transmit High Score
Player <-- HighScoreManager: view High Scores
end
@enduml