@startuml
title AubieMemory System Sequence Diagram
actor Player
participant MemoryGame
participant HighScoreManager
group SD: Memory

Player -> MemoryGame: Choose difficulty
Player <-- MemoryGame: display buttons
loop while (game in progress)
Player <-- MemoryGame: play tone sequence
Player -> MemoryGame: input sequence

alt correct input
Player <- MemoryGame: extend sequence
Player <-- MemoryGame: update score
opt score > high score
MemoryGame --> HighScoreManager: transmit High Score
Player <-- MemoryGame: update high score
end
else incorrect input
     Player <- MemoryGame: end game
     Player <- MemoryGame: display 'play again' button
end

end

Player -> MemoryGame: view high scores
Player <-- HighScoreManager: show high scores
end
@enduml