@startuml
title AubieMemory Use Case Diagram

actor Player

rectangle {
Player --> (choose difficulty)
Player --> (view high scores)
Player --> (play game)
Player --> (mute audio)
(play game) ..> (view buttons): <<includes>>
(play game) ..> (replicate sequence): <<includes>>
(replicate sequence) ..> (press button): <<includes>>
}
@enduml