@startuml
title AubieMemory Use Case Diagram

actor Player

rectangle {
Player --> (choose difficulty)
Player --> (view high scores)

(choose difficulty) ..> (replicate sequence): <<includes>>
(replicate sequence) ..> (view buttons): <<includes>>
(replicate sequence) ..> (play tone): <<includes>>
}
@enduml